# -*- coding: utf-8 -*-



{
    'name': 'Edsys Education Fee Master',
    'version': '1.0',
    'category': 'Edsys Education',
    "sequence": 4,
    'summary': 'Manage Fee structure',
    'complexity': "easy",
    'description': """
            This module provide fee management system over OpenERP
    """,
    'author': 'Redbytes Software Solutions',
    'website': 'edsys.com',
    'images': [],
    'depends': ['base','account_voucher','account'],
    'data': ['security/fees_security.xml',
             'security/ir.model.access.csv',
             'view/sequence_view.xml',
             'view/fees_structure_view.xml',
             'view/fee_calculation_view.xml',
             'view/student_fee_invoice_view.xml',
             'view/Fee_payment_type.xml',
             'view/fee_history_view.xml',
             'view/account_payment_inherit.xml',
             'view/student_fee_payment.xml',
             'view/student_fee_payment_view.xml',
             'view/product_fees_view.xml',
             'view/fees_discount_view.xml',
             'view/product_fees_view.xml',
             'view/fees_discount_view.xml',
             'view/fee_next_year_advance_view.xml',
             'view/resend_payfort_voucher_view.xml',
             'wizard/parent_payment_report_wiz.xml',
             'wizard/student_payment_report_wiz.xml',
             'wizard/resend_pay_fort_link.xml',
             'wizard/payfort_link_reminder_view.xml',
             'wizard/reconcile_advance_payment.xml',
             'wizard/send_receipt_view.xml',
	     	 'report/header_footer_view.xml',
             'report/parent_payment_report.xml',
             'report/student_payment_report.xml',
             'report/student_payment_receipt_fee.xml',
             'report/fees_receipt.xml',
             'view/email_template.xml',
             'wizard/resend_payfort_link_voucher_view.xml',
             'view/send_voucher_mail_cron_view.xml',
             'wizard/reconcile_invoice_with_advance_payment.xml',
             'view/menu_view.xml',
             ],


    'demo': [],
    'css': [],
    'qweb': [],
    'js': [],
    'test': [],
    'images': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
